; generated by Slic3r 1.2.9 on 2019-08-14 at 18:00:32

; For G-Code Optimization - See Desktop>Robot Projects>Preparing To Print>Printing Instructions

; external perimeters extrusion width = 11.00mm
; perimeters extrusion width = 11.00mm
; infill extrusion width = 8.50mm
; solid infill extrusion width = 8.50mm
; top infill extrusion width = 8.50mm

M190 S95 ; set bed temperature
M104 S225 ; set temperature

M109 S225 ; wait for temperature to be reached
G21 ; set units to millimeters
G90 ; use absolute coordinates
M82 ; use absolute distances for extrusion
G92 E0 ; reset extrusion distance
G1 E-0.10000 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z20.000 F30000.000 ; lift Z
G1 X-153.572 Y-101.072 F30000.000 ; move to first infill point
G1 Z3.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X153.572 Y-101.072 E959.19583 F4200.000 ; infill
G1 X153.572 Y101.072 E1590.41574 ; infill
G1 X-153.572 Y101.072 E2549.51156 ; infill
G1 X-153.572 Y-99.722 E3176.51593 ; infill
G1 F24000
G1 X-153.572 Y-101.072 F30000.000 ; move to first wipe and retract point
G1 X153.572 Y-101.072 E0.0 F4200.000 ; wipe and retract
G1 E3176.41593 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z23.000 F30000.000 ; lift Z
G1 X-145.696 Y-93.196 F30000.000 ; move to first infill point
G1 Z3.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X145.696 Y-93.196 E910.01143 F4200.000 ; infill
G1 X145.696 Y93.196 E1492.04694 ; infill
G1 X-145.696 Y93.196 E2401.95836 ; infill
G1 X-145.696 Y-91.846 E2979.77833 ; infill
G1 F24000
G1 X-145.696 Y-93.196 F30000.000 ; move to first wipe and retract point
G1 X145.696 Y-93.196 E0.0 F4200.000 ; wipe and retract
G1 E2979.67833 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z23.000 F30000.000 ; lift Z
G1 X-137.832 Y-85.311 F30000.000 ; move to first infill point
G1 Z3.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X137.775 Y-85.311 E860.71847 F4200.000 ; infill
G1 X137.775 Y85.296 E1393.46103 ; infill
G1 X-137.832 Y85.296 E2254.07951 ; infill
G1 X-137.832 Y-83.961 E2782.60652 ; infill
G1 F24000
G1 X-137.832 Y-85.311 F30000.000 ; move to first wipe and retract point
G1 X137.775 Y-85.311 E0.0 F4200.000 ; wipe and retract
G1 E2782.50652 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z23.000 F30000.000 ; lift Z
G1 X-129.956 Y-77.436 F30000.000 ; move to first infill point
G1 Z3.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X129.900 Y-77.436 E811.53407 F4200.000 ; infill
G1 X129.900 Y77.420 E1295.09223 ; infill
G1 X-129.956 Y77.420 E2106.52631 ; infill
G1 X-129.956 Y-76.086 E2585.86892 ; infill
G1 F24000
G1 X-129.956 Y-77.436 F30000.000 ; move to first wipe and retract point
G1 X129.900 Y-77.436 E0.0 F4200.000 ; wipe and retract
G1 E2585.76892 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z23.000 F30000.000 ; lift Z
G1 X-153.572 Y-101.072 F30000.000 ; move to first infill point
G1 Z6.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X153.572 Y-101.072 E959.19583 F4200.000 ; infill
G1 X153.572 Y101.072 E1590.41574 ; infill
G1 X-153.572 Y101.072 E2549.51156 ; infill
G1 X-153.572 Y-99.722 E3176.51593 ; infill
G1 F24000
G1 X-153.572 Y-101.072 F30000.000 ; move to first wipe and retract point
G1 X153.572 Y-101.072 E0.0 F4200.000 ; wipe and retract
G1 E3176.41593 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z26.000 F30000.000 ; lift Z
G1 X-145.696 Y-93.196 F30000.000 ; move to first infill point
G1 Z6.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X145.696 Y-93.196 E910.01143 F4200.000 ; infill
G1 X145.696 Y93.196 E1492.04694 ; infill
G1 X-145.696 Y93.196 E2401.95836 ; infill
G1 X-145.696 Y-91.846 E2979.77833 ; infill
G1 F24000
G1 X-145.696 Y-93.196 F30000.000 ; move to first wipe and retract point
G1 X145.696 Y-93.196 E0.0 F4200.000 ; wipe and retract
G1 E2979.67833 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z26.000 F30000.000 ; lift Z
G1 X-137.832 Y-85.311 F30000.000 ; move to first infill point
G1 Z6.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X137.775 Y-85.311 E860.71847 F4200.000 ; infill
G1 X137.775 Y85.296 E1393.46103 ; infill
G1 X-137.832 Y85.296 E2254.07951 ; infill
G1 X-137.832 Y-83.961 E2782.60652 ; infill
G1 F24000
G1 X-137.832 Y-85.311 F30000.000 ; move to first wipe and retract point
G1 X137.775 Y-85.311 E0.0 F4200.000 ; wipe and retract
G1 E2782.50652 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z26.000 F30000.000 ; lift Z
G1 X-129.956 Y-77.436 F30000.000 ; move to first infill point
G1 Z6.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X129.900 Y-77.436 E811.53407 F4200.000 ; infill
G1 X129.900 Y77.420 E1295.09223 ; infill
G1 X-129.956 Y77.420 E2106.52631 ; infill
G1 X-129.956 Y-76.086 E2585.86892 ; infill
G1 F24000
G1 X-129.956 Y-77.436 F30000.000 ; move to first wipe and retract point
G1 X129.900 Y-77.436 E0.0 F4200.000 ; wipe and retract
G1 E2585.76892 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z26.000 F30000.000 ; lift Z
G1 X-153.572 Y-101.072 F30000.000 ; move to first infill point
G1 Z9.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X153.572 Y-101.072 E959.19583 F4200.000 ; infill
G1 X153.572 Y101.072 E1590.41574 ; infill
G1 X-153.572 Y101.072 E2549.51156 ; infill
G1 X-153.572 Y-99.722 E3176.51593 ; infill
G1 F24000
G1 X-153.572 Y-101.072 F30000.000 ; move to first wipe and retract point
G1 X153.572 Y-101.072 E0.0 F4200.000 ; wipe and retract
G1 E3176.41593 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z29.000 F30000.000 ; lift Z
G1 X-145.696 Y-93.196 F30000.000 ; move to first infill point
G1 Z9.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X145.696 Y-93.196 E910.01143 F4200.000 ; infill
G1 X145.696 Y93.196 E1492.04694 ; infill
G1 X-145.696 Y93.196 E2401.95836 ; infill
G1 X-145.696 Y-91.846 E2979.77833 ; infill
G1 F24000
G1 X-145.696 Y-93.196 F30000.000 ; move to first wipe and retract point
G1 X145.696 Y-93.196 E0.0 F4200.000 ; wipe and retract
G1 E2979.67833 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z29.000 F30000.000 ; lift Z
G1 X-137.832 Y-85.311 F30000.000 ; move to first infill point
G1 Z9.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X137.775 Y-85.311 E860.71847 F4200.000 ; infill
G1 X137.775 Y85.296 E1393.46103 ; infill
G1 X-137.832 Y85.296 E2254.07951 ; infill
G1 X-137.832 Y-83.961 E2782.60652 ; infill
G1 F24000
G1 X-137.832 Y-85.311 F30000.000 ; move to first wipe and retract point
G1 X137.775 Y-85.311 E0.0 F4200.000 ; wipe and retract
G1 E2782.50652 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z29.000 F30000.000 ; lift Z
G1 X-129.956 Y-77.436 F30000.000 ; move to first infill point
G1 Z9.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X129.900 Y-77.436 E811.53407 F4200.000 ; infill
G1 X129.900 Y77.420 E1295.09223 ; infill
G1 X-129.956 Y77.420 E2106.52631 ; infill
G1 X-129.956 Y-76.086 E2585.86892 ; infill
G1 F24000
G1 X-129.956 Y-77.436 F30000.000 ; move to first wipe and retract point
G1 X129.900 Y-77.436 E0.0 F4200.000 ; wipe and retract
G1 E2585.76892 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z29.000 F30000.000 ; lift Z
G1 X-153.572 Y-101.072 F30000.000 ; move to first infill point
G1 Z12.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X153.572 Y-101.072 E959.19583 F4200.000 ; infill
G1 X153.572 Y101.072 E1590.41574 ; infill
G1 X-153.572 Y101.072 E2549.51156 ; infill
G1 X-153.572 Y-99.722 E3176.51593 ; infill
G1 F24000
G1 X-153.572 Y-101.072 F30000.000 ; move to first wipe and retract point
G1 X153.572 Y-101.072 E0.0 F4200.000 ; wipe and retract
G1 E3176.41593 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z32.000 F30000.000 ; lift Z
G1 X-145.696 Y-93.196 F30000.000 ; move to first infill point
G1 Z12.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X145.696 Y-93.196 E910.01143 F4200.000 ; infill
G1 X145.696 Y93.196 E1492.04694 ; infill
G1 X-145.696 Y93.196 E2401.95836 ; infill
G1 X-145.696 Y-91.846 E2979.77833 ; infill
G1 F24000
G1 X-145.696 Y-93.196 F30000.000 ; move to first wipe and retract point
G1 X145.696 Y-93.196 E0.0 F4200.000 ; wipe and retract
G1 E2979.67833 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z32.000 F30000.000 ; lift Z
G1 X-137.832 Y-85.311 F30000.000 ; move to first infill point
G1 Z12.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X137.775 Y-85.311 E860.71847 F4200.000 ; infill
G1 X137.775 Y85.296 E1393.46103 ; infill
G1 X-137.832 Y85.296 E2254.07951 ; infill
G1 X-137.832 Y-83.961 E2782.60652 ; infill
G1 F24000
G1 X-137.832 Y-85.311 F30000.000 ; move to first wipe and retract point
G1 X137.775 Y-85.311 E0.0 F4200.000 ; wipe and retract
G1 E2782.50652 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z32.000 F30000.000 ; lift Z
G1 X-129.956 Y-77.436 F30000.000 ; move to first infill point
G1 Z12.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X129.900 Y-77.436 E811.53407 F4200.000 ; infill
G1 X129.900 Y77.420 E1295.09223 ; infill
G1 X-129.956 Y77.420 E2106.52631 ; infill
G1 X-129.956 Y-76.086 E2585.86892 ; infill
G1 F24000
G1 X-129.956 Y-77.436 F30000.000 ; move to first wipe and retract point
G1 X129.900 Y-77.436 E0.0 F4200.000 ; wipe and retract
G1 E2585.76892 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z32.000 F30000.000 ; lift Z
G1 X-153.572 Y-101.072 F30000.000 ; move to first infill point
G1 Z15.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X153.572 Y-101.072 E959.19583 F4200.000 ; infill
G1 X153.572 Y101.072 E1590.41574 ; infill
G1 X-153.572 Y101.072 E2549.51156 ; infill
G1 X-153.572 Y-99.722 E3176.51593 ; infill
G1 F24000
G1 X-153.572 Y-101.072 F30000.000 ; move to first wipe and retract point
G1 X153.572 Y-101.072 E0.0 F4200.000 ; wipe and retract
G1 E3176.41593 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z35.000 F30000.000 ; lift Z
G1 X-145.696 Y-93.196 F30000.000 ; move to first infill point
G1 Z15.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X145.696 Y-93.196 E910.01143 F4200.000 ; infill
G1 X145.696 Y93.196 E1492.04694 ; infill
G1 X-145.696 Y93.196 E2401.95836 ; infill
G1 X-145.696 Y-91.846 E2979.77833 ; infill
G1 F24000
G1 X-145.696 Y-93.196 F30000.000 ; move to first wipe and retract point
G1 X145.696 Y-93.196 E0.0 F4200.000 ; wipe and retract
G1 E2979.67833 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z35.000 F30000.000 ; lift Z
G1 X-137.832 Y-85.311 F30000.000 ; move to first infill point
G1 Z15.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X137.775 Y-85.311 E860.71847 F4200.000 ; infill
G1 X137.775 Y85.296 E1393.46103 ; infill
G1 X-137.832 Y85.296 E2254.07951 ; infill
G1 X-137.832 Y-83.961 E2782.60652 ; infill
G1 F24000
G1 X-137.832 Y-85.311 F30000.000 ; move to first wipe and retract point
G1 X137.775 Y-85.311 E0.0 F4200.000 ; wipe and retract
G1 E2782.50652 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z35.000 F30000.000 ; lift Z
G1 X-129.956 Y-77.436 F30000.000 ; move to first infill point
G1 Z15.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X129.900 Y-77.436 E811.53407 F4200.000 ; infill
G1 X129.900 Y77.420 E1295.09223 ; infill
G1 X-129.956 Y77.420 E2106.52631 ; infill
G1 X-129.956 Y-76.086 E2585.86892 ; infill
G1 F24000
G1 X-129.956 Y-77.436 F30000.000 ; move to first wipe and retract point
G1 X129.900 Y-77.436 E0.0 F4200.000 ; wipe and retract
G1 E2585.76892 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z35.000 F30000.000 ; lift Z
G1 X-153.572 Y-101.072 F30000.000 ; move to first infill point
G1 Z18.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X153.572 Y-101.072 E959.19583 F4200.000 ; infill
G1 X153.572 Y101.072 E1590.41574 ; infill
G1 X-153.572 Y101.072 E2549.51156 ; infill
G1 X-153.572 Y-99.722 E3176.51593 ; infill
G1 F24000
G1 X-153.572 Y-101.072 F30000.000 ; move to first wipe and retract point
G1 X153.572 Y-101.072 E0.0 F4200.000 ; wipe and retract
G1 E3176.41593 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z38.000 F30000.000 ; lift Z
G1 X-145.696 Y-93.196 F30000.000 ; move to first infill point
G1 Z18.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X145.696 Y-93.196 E910.01143 F4200.000 ; infill
G1 X145.696 Y93.196 E1492.04694 ; infill
G1 X-145.696 Y93.196 E2401.95836 ; infill
G1 X-145.696 Y-91.846 E2979.77833 ; infill
G1 F24000
G1 X-145.696 Y-93.196 F30000.000 ; move to first wipe and retract point
G1 X145.696 Y-93.196 E0.0 F4200.000 ; wipe and retract
G1 E2979.67833 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z38.000 F30000.000 ; lift Z
G1 X-137.832 Y-85.311 F30000.000 ; move to first infill point
G1 Z18.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X137.775 Y-85.311 E860.71847 F4200.000 ; infill
G1 X137.775 Y85.296 E1393.46103 ; infill
G1 X-137.832 Y85.296 E2254.07951 ; infill
G1 X-137.832 Y-83.961 E2782.60652 ; infill
G1 F24000
G1 X-137.832 Y-85.311 F30000.000 ; move to first wipe and retract point
G1 X137.775 Y-85.311 E0.0 F4200.000 ; wipe and retract
G1 E2782.50652 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z38.000 F30000.000 ; lift Z
G1 X-129.956 Y-77.436 F30000.000 ; move to first infill point
G1 Z18.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X129.900 Y-77.436 E811.53407 F4200.000 ; infill
G1 X129.900 Y77.420 E1295.09223 ; infill
G1 X-129.956 Y77.420 E2106.52631 ; infill
G1 X-129.956 Y-76.086 E2585.86892 ; infill
G1 F24000
G1 X-129.956 Y-77.436 F30000.000 ; move to first wipe and retract point
G1 X129.900 Y-77.436 E0.0 F4200.000 ; wipe and retract
G1 E2585.76892 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z38.000 F30000.000 ; lift Z
G1 X-153.572 Y-101.072 F30000.000 ; move to first infill point
G1 Z21.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X153.572 Y-101.072 E959.19583 F4200.000 ; infill
G1 X153.572 Y101.072 E1590.41574 ; infill
G1 X-153.572 Y101.072 E2549.51156 ; infill
G1 X-153.572 Y-99.722 E3176.51593 ; infill
G1 F24000
G1 X-153.572 Y-101.072 F30000.000 ; move to first wipe and retract point
G1 X153.572 Y-101.072 E0.0 F4200.000 ; wipe and retract
G1 E3176.41593 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z41.000 F30000.000 ; lift Z
G1 X-145.696 Y-93.196 F30000.000 ; move to first infill point
G1 Z21.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X145.696 Y-93.196 E910.01143 F4200.000 ; infill
G1 X145.696 Y93.196 E1492.04694 ; infill
G1 X-145.696 Y93.196 E2401.95836 ; infill
G1 X-145.696 Y-91.846 E2979.77833 ; infill
G1 F24000
G1 X-145.696 Y-93.196 F30000.000 ; move to first wipe and retract point
G1 X145.696 Y-93.196 E0.0 F4200.000 ; wipe and retract
G1 E2979.67833 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z41.000 F30000.000 ; lift Z
G1 X-137.832 Y-85.311 F30000.000 ; move to first infill point
G1 Z21.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X137.775 Y-85.311 E860.71847 F4200.000 ; infill
G1 X137.775 Y85.296 E1393.46103 ; infill
G1 X-137.832 Y85.296 E2254.07951 ; infill
G1 X-137.832 Y-83.961 E2782.60652 ; infill
G1 F24000
G1 X-137.832 Y-85.311 F30000.000 ; move to first wipe and retract point
G1 X137.775 Y-85.311 E0.0 F4200.000 ; wipe and retract
G1 E2782.50652 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z41.000 F30000.000 ; lift Z
G1 X-129.956 Y-77.436 F30000.000 ; move to first infill point
G1 Z21.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X129.900 Y-77.436 E811.53407 F4200.000 ; infill
G1 X129.900 Y77.420 E1295.09223 ; infill
G1 X-129.956 Y77.420 E2106.52631 ; infill
G1 X-129.956 Y-76.086 E2585.86892 ; infill
G1 F24000
G1 X-129.956 Y-77.436 F30000.000 ; move to first wipe and retract point
G1 X129.900 Y-77.436 E0.0 F4200.000 ; wipe and retract
G1 E2585.76892 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z41.000 F30000.000 ; lift Z
G1 X-153.572 Y-101.072 F30000.000 ; move to first infill point
G1 Z24.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X153.572 Y-101.072 E959.19583 F4200.000 ; infill
G1 X153.572 Y101.072 E1590.41574 ; infill
G1 X-153.572 Y101.072 E2549.51156 ; infill
G1 X-153.572 Y-99.722 E3176.51593 ; infill
G1 F24000
G1 X-153.572 Y-101.072 F30000.000 ; move to first wipe and retract point
G1 X153.572 Y-101.072 E0.0 F4200.000 ; wipe and retract
G1 E3176.41593 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z44.000 F30000.000 ; lift Z
G1 X-145.696 Y-93.196 F30000.000 ; move to first infill point
G1 Z24.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X145.696 Y-93.196 E910.01143 F4200.000 ; infill
G1 X145.696 Y93.196 E1492.04694 ; infill
G1 X-145.696 Y93.196 E2401.95836 ; infill
G1 X-145.696 Y-91.846 E2979.77833 ; infill
G1 F24000
G1 X-145.696 Y-93.196 F30000.000 ; move to first wipe and retract point
G1 X145.696 Y-93.196 E0.0 F4200.000 ; wipe and retract
G1 E2979.67833 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z44.000 F30000.000 ; lift Z
G1 X-137.832 Y-85.311 F30000.000 ; move to first infill point
G1 Z24.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X137.775 Y-85.311 E860.71847 F4200.000 ; infill
G1 X137.775 Y85.296 E1393.46103 ; infill
G1 X-137.832 Y85.296 E2254.07951 ; infill
G1 X-137.832 Y-83.961 E2782.60652 ; infill
G1 F24000
G1 X-137.832 Y-85.311 F30000.000 ; move to first wipe and retract point
G1 X137.775 Y-85.311 E0.0 F4200.000 ; wipe and retract
G1 E2782.50652 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z44.000 F30000.000 ; lift Z
G1 X-129.956 Y-77.436 F30000.000 ; move to first infill point
G1 Z24.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X129.900 Y-77.436 E811.53407 F4200.000 ; infill
G1 X129.900 Y77.420 E1295.09223 ; infill
G1 X-129.956 Y77.420 E2106.52631 ; infill
G1 X-129.956 Y-76.086 E2585.86892 ; infill
G1 F24000
G1 X-129.956 Y-77.436 F30000.000 ; move to first wipe and retract point
G1 X129.900 Y-77.436 E0.0 F4200.000 ; wipe and retract
G1 E2585.76892 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z44.000 F30000.000 ; lift Z
G1 X-153.572 Y-101.072 F30000.000 ; move to first infill point
G1 Z27.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X153.572 Y-101.072 E959.19583 F4200.000 ; infill
G1 X153.572 Y101.072 E1590.41574 ; infill
G1 X-153.572 Y101.072 E2549.51156 ; infill
G1 X-153.572 Y-99.722 E3176.51593 ; infill
G1 F24000
G1 X-153.572 Y-101.072 F30000.000 ; move to first wipe and retract point
G1 X153.572 Y-101.072 E0.0 F4200.000 ; wipe and retract
G1 E3176.41593 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z47.000 F30000.000 ; lift Z
G1 X-145.696 Y-93.196 F30000.000 ; move to first infill point
G1 Z27.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X145.696 Y-93.196 E910.01143 F4200.000 ; infill
G1 X145.696 Y93.196 E1492.04694 ; infill
G1 X-145.696 Y93.196 E2401.95836 ; infill
G1 X-145.696 Y-91.846 E2979.77833 ; infill
G1 F24000
G1 X-145.696 Y-93.196 F30000.000 ; move to first wipe and retract point
G1 X145.696 Y-93.196 E0.0 F4200.000 ; wipe and retract
G1 E2979.67833 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z47.000 F30000.000 ; lift Z
G1 X-137.832 Y-85.311 F30000.000 ; move to first infill point
G1 Z27.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X137.775 Y-85.311 E860.71847 F4200.000 ; infill
G1 X137.775 Y85.296 E1393.46103 ; infill
G1 X-137.832 Y85.296 E2254.07951 ; infill
G1 X-137.832 Y-83.961 E2782.60652 ; infill
G1 F24000
G1 X-137.832 Y-85.311 F30000.000 ; move to first wipe and retract point
G1 X137.775 Y-85.311 E0.0 F4200.000 ; wipe and retract
G1 E2782.50652 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z47.000 F30000.000 ; lift Z
G1 X-129.956 Y-77.436 F30000.000 ; move to first infill point
G1 Z27.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X129.900 Y-77.436 E811.53407 F4200.000 ; infill
G1 X129.900 Y77.420 E1295.09223 ; infill
G1 X-129.956 Y77.420 E2106.52631 ; infill
G1 X-129.956 Y-76.086 E2585.86892 ; infill
G1 F24000
G1 X-129.956 Y-77.436 F30000.000 ; move to first wipe and retract point
G1 X129.900 Y-77.436 E0.0 F4200.000 ; wipe and retract
G1 E2585.76892 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z47.000 F30000.000 ; lift Z
G1 X-153.572 Y-101.072 F30000.000 ; move to first infill point
G1 Z30.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X153.572 Y-101.072 E959.19583 F4200.000 ; infill
G1 X153.572 Y101.072 E1590.41574 ; infill
G1 X-153.572 Y101.072 E2549.51156 ; infill
G1 X-153.572 Y-99.722 E3176.51593 ; infill
G1 F24000
G1 X-153.572 Y-101.072 F30000.000 ; move to first wipe and retract point
G1 X153.572 Y-101.072 E0.0 F4200.000 ; wipe and retract
G1 E3176.41593 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z50.000 F30000.000 ; lift Z
G1 X-145.696 Y-93.196 F30000.000 ; move to first infill point
G1 Z30.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X145.696 Y-93.196 E910.01143 F4200.000 ; infill
G1 X145.696 Y93.196 E1492.04694 ; infill
G1 X-145.696 Y93.196 E2401.95836 ; infill
G1 X-145.696 Y-91.846 E2979.77833 ; infill
G1 F24000
G1 X-145.696 Y-93.196 F30000.000 ; move to first wipe and retract point
G1 X145.696 Y-93.196 E0.0 F4200.000 ; wipe and retract
G1 E2979.67833 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z50.000 F30000.000 ; lift Z
G1 X-137.832 Y-85.311 F30000.000 ; move to first infill point
G1 Z30.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X137.775 Y-85.311 E860.71847 F4200.000 ; infill
G1 X137.775 Y85.296 E1393.46103 ; infill
G1 X-137.832 Y85.296 E2254.07951 ; infill
G1 X-137.832 Y-83.961 E2782.60652 ; infill
G1 F24000
G1 X-137.832 Y-85.311 F30000.000 ; move to first wipe and retract point
G1 X137.775 Y-85.311 E0.0 F4200.000 ; wipe and retract
G1 E2782.50652 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z50.000 F30000.000 ; lift Z
G1 X-129.956 Y-77.436 F30000.000 ; move to first infill point
G1 Z30.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X129.900 Y-77.436 E811.53407 F4200.000 ; infill
G1 X129.900 Y77.420 E1295.09223 ; infill
G1 X-129.956 Y77.420 E2106.52631 ; infill
G1 X-129.956 Y-76.086 E2585.86892 ; infill
G1 F24000
G1 X-129.956 Y-77.436 F30000.000 ; move to first wipe and retract point
G1 X129.900 Y-77.436 E0.0 F4200.000 ; wipe and retract
G1 E2585.76892 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z50.000 F30000.000 ; lift Z
G1 X-153.572 Y-101.072 F30000.000 ; move to first infill point
G1 Z33.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X153.572 Y-101.072 E959.19583 F4200.000 ; infill
G1 X153.572 Y101.072 E1590.41574 ; infill
G1 X-153.572 Y101.072 E2549.51156 ; infill
G1 X-153.572 Y-99.722 E3176.51593 ; infill
G1 F24000
G1 X-153.572 Y-101.072 F30000.000 ; move to first wipe and retract point
G1 X153.572 Y-101.072 E0.0 F4200.000 ; wipe and retract
G1 E3176.41593 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z53.000 F30000.000 ; lift Z
G1 X-145.696 Y-93.196 F30000.000 ; move to first infill point
G1 Z33.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X145.696 Y-93.196 E910.01143 F4200.000 ; infill
G1 X145.696 Y93.196 E1492.04694 ; infill
G1 X-145.696 Y93.196 E2401.95836 ; infill
G1 X-145.696 Y-91.846 E2979.77833 ; infill
G1 F24000
G1 X-145.696 Y-93.196 F30000.000 ; move to first wipe and retract point
G1 X145.696 Y-93.196 E0.0 F4200.000 ; wipe and retract
G1 E2979.67833 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z53.000 F30000.000 ; lift Z
G1 X-137.832 Y-85.311 F30000.000 ; move to first infill point
G1 Z33.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X137.775 Y-85.311 E860.71847 F4200.000 ; infill
G1 X137.775 Y85.296 E1393.46103 ; infill
G1 X-137.832 Y85.296 E2254.07951 ; infill
G1 X-137.832 Y-83.961 E2782.60652 ; infill
G1 F24000
G1 X-137.832 Y-85.311 F30000.000 ; move to first wipe and retract point
G1 X137.775 Y-85.311 E0.0 F4200.000 ; wipe and retract
G1 E2782.50652 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z53.000 F30000.000 ; lift Z
G1 X-129.956 Y-77.436 F30000.000 ; move to first infill point
G1 Z33.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X129.900 Y-77.436 E811.53407 F4200.000 ; infill
G1 X129.900 Y77.420 E1295.09223 ; infill
G1 X-129.956 Y77.420 E2106.52631 ; infill
G1 X-129.956 Y-76.086 E2585.86892 ; infill
G1 F24000
G1 X-129.956 Y-77.436 F30000.000 ; move to first wipe and retract point
G1 X129.900 Y-77.436 E0.0 F4200.000 ; wipe and retract
G1 E2585.76892 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z53.000 F30000.000 ; lift Z
G1 X-153.572 Y-101.072 F30000.000 ; move to first infill point
G1 Z36.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X153.572 Y-101.072 E959.19583 F4200.000 ; infill
G1 X153.572 Y101.072 E1590.41574 ; infill
G1 X-153.572 Y101.072 E2549.51156 ; infill
G1 X-153.572 Y-99.722 E3176.51593 ; infill
G1 F24000
G1 X-153.572 Y-101.072 F30000.000 ; move to first wipe and retract point
G1 X153.572 Y-101.072 E0.0 F4200.000 ; wipe and retract
G1 E3176.41593 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z56.000 F30000.000 ; lift Z
G1 X-145.696 Y-93.196 F30000.000 ; move to first infill point
G1 Z36.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X145.696 Y-93.196 E910.01143 F4200.000 ; infill
G1 X145.696 Y93.196 E1492.04694 ; infill
G1 X-145.696 Y93.196 E2401.95836 ; infill
G1 X-145.696 Y-91.846 E2979.77833 ; infill
G1 F24000
G1 X-145.696 Y-93.196 F30000.000 ; move to first wipe and retract point
G1 X145.696 Y-93.196 E0.0 F4200.000 ; wipe and retract
G1 E2979.67833 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z56.000 F30000.000 ; lift Z
G1 X-137.832 Y-85.311 F30000.000 ; move to first infill point
G1 Z36.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X137.775 Y-85.311 E860.71847 F4200.000 ; infill
G1 X137.775 Y85.296 E1393.46103 ; infill
G1 X-137.832 Y85.296 E2254.07951 ; infill
G1 X-137.832 Y-83.961 E2782.60652 ; infill
G1 F24000
G1 X-137.832 Y-85.311 F30000.000 ; move to first wipe and retract point
G1 X137.775 Y-85.311 E0.0 F4200.000 ; wipe and retract
G1 E2782.50652 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z56.000 F30000.000 ; lift Z
G1 X-129.956 Y-77.436 F30000.000 ; move to first infill point
G1 Z36.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X129.900 Y-77.436 E811.53407 F4200.000 ; infill
G1 X129.900 Y77.420 E1295.09223 ; infill
G1 X-129.956 Y77.420 E2106.52631 ; infill
G1 X-129.956 Y-76.086 E2585.86892 ; infill
G1 F24000
G1 X-129.956 Y-77.436 F30000.000 ; move to first wipe and retract point
G1 X129.900 Y-77.436 E0.0 F4200.000 ; wipe and retract
G1 E2585.76892 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z56.000 F30000.000 ; lift Z
G1 X-153.572 Y-101.072 F30000.000 ; move to first infill point
G1 Z39.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X153.572 Y-101.072 E959.19583 F4200.000 ; infill
G1 X153.572 Y101.072 E1590.41574 ; infill
G1 X-153.572 Y101.072 E2549.51156 ; infill
G1 X-153.572 Y-99.722 E3176.51593 ; infill
G1 F24000
G1 X-153.572 Y-101.072 F30000.000 ; move to first wipe and retract point
G1 X153.572 Y-101.072 E0.0 F4200.000 ; wipe and retract
G1 E3176.41593 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z59.000 F30000.000 ; lift Z
G1 X-145.696 Y-93.196 F30000.000 ; move to first infill point
G1 Z39.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X145.696 Y-93.196 E910.01143 F4200.000 ; infill
G1 X145.696 Y93.196 E1492.04694 ; infill
G1 X-145.696 Y93.196 E2401.95836 ; infill
G1 X-145.696 Y-91.846 E2979.77833 ; infill
G1 F24000
G1 X-145.696 Y-93.196 F30000.000 ; move to first wipe and retract point
G1 X145.696 Y-93.196 E0.0 F4200.000 ; wipe and retract
G1 E2979.67833 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z59.000 F30000.000 ; lift Z
G1 X-137.832 Y-85.311 F30000.000 ; move to first infill point
G1 Z39.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X137.775 Y-85.311 E860.71847 F4200.000 ; infill
G1 X137.775 Y85.296 E1393.46103 ; infill
G1 X-137.832 Y85.296 E2254.07951 ; infill
G1 X-137.832 Y-83.961 E2782.60652 ; infill
G1 F24000
G1 X-137.832 Y-85.311 F30000.000 ; move to first wipe and retract point
G1 X137.775 Y-85.311 E0.0 F4200.000 ; wipe and retract
G1 E2782.50652 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z59.000 F30000.000 ; lift Z
G1 X-129.956 Y-77.436 F30000.000 ; move to first infill point
G1 Z39.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X129.900 Y-77.436 E811.53407 F4200.000 ; infill
G1 X129.900 Y77.420 E1295.09223 ; infill
G1 X-129.956 Y77.420 E2106.52631 ; infill
G1 X-129.956 Y-76.086 E2585.86892 ; infill
G1 F24000
G1 X-129.956 Y-77.436 F30000.000 ; move to first wipe and retract point
G1 X129.900 Y-77.436 E0.0 F4200.000 ; wipe and retract
G1 E2585.76892 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z59.000 F30000.000 ; lift Z
G1 X-153.572 Y-101.072 F30000.000 ; move to first infill point
G1 Z42.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X153.572 Y-101.072 E959.19583 F4200.000 ; infill
G1 X153.572 Y101.072 E1590.41574 ; infill
G1 X-153.572 Y101.072 E2549.51156 ; infill
G1 X-153.572 Y-99.722 E3176.51593 ; infill
G1 F24000
G1 X-153.572 Y-101.072 F30000.000 ; move to first wipe and retract point
G1 X153.572 Y-101.072 E0.0 F4200.000 ; wipe and retract
G1 E3176.41593 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z62.000 F30000.000 ; lift Z
G1 X-145.696 Y-93.196 F30000.000 ; move to first infill point
G1 Z42.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X145.696 Y-93.196 E910.01143 F4200.000 ; infill
G1 X145.696 Y93.196 E1492.04694 ; infill
G1 X-145.696 Y93.196 E2401.95836 ; infill
G1 X-145.696 Y-91.846 E2979.77833 ; infill
G1 F24000
G1 X-145.696 Y-93.196 F30000.000 ; move to first wipe and retract point
G1 X145.696 Y-93.196 E0.0 F4200.000 ; wipe and retract
G1 E2979.67833 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z62.000 F30000.000 ; lift Z
G1 X-137.832 Y-85.311 F30000.000 ; move to first infill point
G1 Z42.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X137.775 Y-85.311 E860.71847 F4200.000 ; infill
G1 X137.775 Y85.296 E1393.46103 ; infill
G1 X-137.832 Y85.296 E2254.07951 ; infill
G1 X-137.832 Y-83.961 E2782.60652 ; infill
G1 F24000
G1 X-137.832 Y-85.311 F30000.000 ; move to first wipe and retract point
G1 X137.775 Y-85.311 E0.0 F4200.000 ; wipe and retract
G1 E2782.50652 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z62.000 F30000.000 ; lift Z
G1 X-129.956 Y-77.436 F30000.000 ; move to first infill point
G1 Z42.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X129.900 Y-77.436 E811.53407 F4200.000 ; infill
G1 X129.900 Y77.420 E1295.09223 ; infill
G1 X-129.956 Y77.420 E2106.52631 ; infill
G1 X-129.956 Y-76.086 E2585.86892 ; infill
G1 F24000
G1 X-129.956 Y-77.436 F30000.000 ; move to first wipe and retract point
G1 X129.900 Y-77.436 E0.0 F4200.000 ; wipe and retract
G1 E2585.76892 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z62.000 F30000.000 ; lift Z
G1 X-153.572 Y-101.072 F30000.000 ; move to first infill point
G1 Z45.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X153.572 Y-101.072 E959.19583 F4200.000 ; infill
G1 X153.572 Y101.072 E1590.41574 ; infill
G1 X-153.572 Y101.072 E2549.51156 ; infill
G1 X-153.572 Y-99.722 E3176.51593 ; infill
G1 F24000
G1 X-153.572 Y-101.072 F30000.000 ; move to first wipe and retract point
G1 X153.572 Y-101.072 E0.0 F4200.000 ; wipe and retract
G1 E3176.41593 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z65.000 F30000.000 ; lift Z
G1 X-145.696 Y-93.196 F30000.000 ; move to first infill point
G1 Z45.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X145.696 Y-93.196 E910.01143 F4200.000 ; infill
G1 X145.696 Y93.196 E1492.04694 ; infill
G1 X-145.696 Y93.196 E2401.95836 ; infill
G1 X-145.696 Y-91.846 E2979.77833 ; infill
G1 F24000
G1 X-145.696 Y-93.196 F30000.000 ; move to first wipe and retract point
G1 X145.696 Y-93.196 E0.0 F4200.000 ; wipe and retract
G1 E2979.67833 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z65.000 F30000.000 ; lift Z
G1 X-137.832 Y-85.311 F30000.000 ; move to first infill point
G1 Z45.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X137.775 Y-85.311 E860.71847 F4200.000 ; infill
G1 X137.775 Y85.296 E1393.46103 ; infill
G1 X-137.832 Y85.296 E2254.07951 ; infill
G1 X-137.832 Y-83.961 E2782.60652 ; infill
G1 F24000
G1 X-137.832 Y-85.311 F30000.000 ; move to first wipe and retract point
G1 X137.775 Y-85.311 E0.0 F4200.000 ; wipe and retract
G1 E2782.50652 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z65.000 F30000.000 ; lift Z
G1 X-129.956 Y-77.436 F30000.000 ; move to first infill point
G1 Z45.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X129.900 Y-77.436 E811.53407 F4200.000 ; infill
G1 X129.900 Y77.420 E1295.09223 ; infill
G1 X-129.956 Y77.420 E2106.52631 ; infill
G1 X-129.956 Y-76.086 E2585.86892 ; infill
G1 F24000
G1 X-129.956 Y-77.436 F30000.000 ; move to first wipe and retract point
G1 X129.900 Y-77.436 E0.0 F4200.000 ; wipe and retract
G1 E2585.76892 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z65.000 F30000.000 ; lift Z
G1 X-153.572 Y-101.072 F30000.000 ; move to first infill point
G1 Z48.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X153.572 Y-101.072 E959.19583 F4200.000 ; infill
G1 X153.572 Y101.072 E1590.41574 ; infill
G1 X-153.572 Y101.072 E2549.51156 ; infill
G1 X-153.572 Y-99.722 E3176.51593 ; infill
G1 F24000
G1 X-153.572 Y-101.072 F30000.000 ; move to first wipe and retract point
G1 X153.572 Y-101.072 E0.0 F4200.000 ; wipe and retract
G1 E3176.41593 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z68.000 F30000.000 ; lift Z
G1 X-145.696 Y-93.196 F30000.000 ; move to first infill point
G1 Z48.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X145.696 Y-93.196 E910.01143 F4200.000 ; infill
G1 X145.696 Y93.196 E1492.04694 ; infill
G1 X-145.696 Y93.196 E2401.95836 ; infill
G1 X-145.696 Y-91.846 E2979.77833 ; infill
G1 F24000
G1 X-145.696 Y-93.196 F30000.000 ; move to first wipe and retract point
G1 X145.696 Y-93.196 E0.0 F4200.000 ; wipe and retract
G1 E2979.67833 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z68.000 F30000.000 ; lift Z
G1 X-137.832 Y-85.311 F30000.000 ; move to first infill point
G1 Z48.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X137.775 Y-85.311 E860.71847 F4200.000 ; infill
G1 X137.775 Y85.296 E1393.46103 ; infill
G1 X-137.832 Y85.296 E2254.07951 ; infill
G1 X-137.832 Y-83.961 E2782.60652 ; infill
G1 F24000
G1 X-137.832 Y-85.311 F30000.000 ; move to first wipe and retract point
G1 X137.775 Y-85.311 E0.0 F4200.000 ; wipe and retract
G1 E2782.50652 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z68.000 F30000.000 ; lift Z
G1 X-129.956 Y-77.436 F30000.000 ; move to first infill point
G1 Z48.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X129.900 Y-77.436 E811.53407 F4200.000 ; infill
G1 X129.900 Y77.420 E1295.09223 ; infill
G1 X-129.956 Y77.420 E2106.52631 ; infill
G1 X-129.956 Y-76.086 E2585.86892 ; infill
G1 F24000
G1 X-129.956 Y-77.436 F30000.000 ; move to first wipe and retract point
G1 X129.900 Y-77.436 E0.0 F4200.000 ; wipe and retract
G1 E2585.76892 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z68.000 F30000.000 ; lift Z
G1 X-153.572 Y-101.072 F30000.000 ; move to first infill point
G1 Z51.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X153.572 Y-101.072 E959.19583 F4200.000 ; infill
G1 X153.572 Y101.072 E1590.41574 ; infill
G1 X-153.572 Y101.072 E2549.51156 ; infill
G1 X-153.572 Y-99.722 E3176.51593 ; infill
G1 F24000
G1 X-153.572 Y-101.072 F30000.000 ; move to first wipe and retract point
G1 X153.572 Y-101.072 E0.0 F4200.000 ; wipe and retract
G1 E3176.41593 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z71.000 F30000.000 ; lift Z
G1 X-145.696 Y-93.196 F30000.000 ; move to first infill point
G1 Z51.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X145.696 Y-93.196 E910.01143 F4200.000 ; infill
G1 X145.696 Y93.196 E1492.04694 ; infill
G1 X-145.696 Y93.196 E2401.95836 ; infill
G1 X-145.696 Y-91.846 E2979.77833 ; infill
G1 F24000
G1 X-145.696 Y-93.196 F30000.000 ; move to first wipe and retract point
G1 X145.696 Y-93.196 E0.0 F4200.000 ; wipe and retract
G1 E2979.67833 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z71.000 F30000.000 ; lift Z
G1 X-137.832 Y-85.311 F30000.000 ; move to first infill point
G1 Z51.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X137.775 Y-85.311 E860.71847 F4200.000 ; infill
G1 X137.775 Y85.296 E1393.46103 ; infill
G1 X-137.832 Y85.296 E2254.07951 ; infill
G1 X-137.832 Y-83.961 E2782.60652 ; infill
G1 F24000
G1 X-137.832 Y-85.311 F30000.000 ; move to first wipe and retract point
G1 X137.775 Y-85.311 E0.0 F4200.000 ; wipe and retract
G1 E2782.50652 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z71.000 F30000.000 ; lift Z
G1 X-129.956 Y-77.436 F30000.000 ; move to first infill point
G1 Z51.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X129.900 Y-77.436 E811.53407 F4200.000 ; infill
G1 X129.900 Y77.420 E1295.09223 ; infill
G1 X-129.956 Y77.420 E2106.52631 ; infill
G1 X-129.956 Y-76.086 E2585.86892 ; infill
G1 F24000
G1 X-129.956 Y-77.436 F30000.000 ; move to first wipe and retract point
G1 X129.900 Y-77.436 E0.0 F4200.000 ; wipe and retract
G1 E2585.76892 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z71.000 F30000.000 ; lift Z
G1 X-153.572 Y-101.072 F30000.000 ; move to first infill point
G1 Z54.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X153.572 Y-101.072 E959.19583 F4200.000 ; infill
G1 X153.572 Y101.072 E1590.41574 ; infill
G1 X-153.572 Y101.072 E2549.51156 ; infill
G1 X-153.572 Y-99.722 E3176.51593 ; infill
G1 F24000
G1 X-153.572 Y-101.072 F30000.000 ; move to first wipe and retract point
G1 X153.572 Y-101.072 E0.0 F4200.000 ; wipe and retract
G1 E3176.41593 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z74.000 F30000.000 ; lift Z
G1 X-145.696 Y-93.196 F30000.000 ; move to first infill point
G1 Z54.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X145.696 Y-93.196 E910.01143 F4200.000 ; infill
G1 X145.696 Y93.196 E1492.04694 ; infill
G1 X-145.696 Y93.196 E2401.95836 ; infill
G1 X-145.696 Y-91.846 E2979.77833 ; infill
G1 F24000
G1 X-145.696 Y-93.196 F30000.000 ; move to first wipe and retract point
G1 X145.696 Y-93.196 E0.0 F4200.000 ; wipe and retract
G1 E2979.67833 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z74.000 F30000.000 ; lift Z
G1 X-137.832 Y-85.311 F30000.000 ; move to first infill point
G1 Z54.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X137.775 Y-85.311 E860.71847 F4200.000 ; infill
G1 X137.775 Y85.296 E1393.46103 ; infill
G1 X-137.832 Y85.296 E2254.07951 ; infill
G1 X-137.832 Y-83.961 E2782.60652 ; infill
G1 F24000
G1 X-137.832 Y-85.311 F30000.000 ; move to first wipe and retract point
G1 X137.775 Y-85.311 E0.0 F4200.000 ; wipe and retract
G1 E2782.50652 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z74.000 F30000.000 ; lift Z
G1 X-129.956 Y-77.436 F30000.000 ; move to first infill point
G1 Z54.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X129.900 Y-77.436 E811.53407 F4200.000 ; infill
G1 X129.900 Y77.420 E1295.09223 ; infill
G1 X-129.956 Y77.420 E2106.52631 ; infill
G1 X-129.956 Y-76.086 E2585.86892 ; infill
G1 F24000
G1 X-129.956 Y-77.436 F30000.000 ; move to first wipe and retract point
G1 X129.900 Y-77.436 E0.0 F4200.000 ; wipe and retract
G1 E2585.76892 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z74.000 F30000.000 ; lift Z
G1 X-153.572 Y-101.072 F30000.000 ; move to first infill point
G1 Z57.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X153.572 Y-101.072 E959.19583 F4200.000 ; infill
G1 X153.572 Y101.072 E1590.41574 ; infill
G1 X-153.572 Y101.072 E2549.51156 ; infill
G1 X-153.572 Y-99.722 E3176.51593 ; infill
G1 F24000
G1 X-153.572 Y-101.072 F30000.000 ; move to first wipe and retract point
G1 X153.572 Y-101.072 E0.0 F4200.000 ; wipe and retract
G1 E3176.41593 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z77.000 F30000.000 ; lift Z
G1 X-145.696 Y-93.196 F30000.000 ; move to first infill point
G1 Z57.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X145.696 Y-93.196 E910.01143 F4200.000 ; infill
G1 X145.696 Y93.196 E1492.04694 ; infill
G1 X-145.696 Y93.196 E2401.95836 ; infill
G1 X-145.696 Y-91.846 E2979.77833 ; infill
G1 F24000
G1 X-145.696 Y-93.196 F30000.000 ; move to first wipe and retract point
G1 X145.696 Y-93.196 E0.0 F4200.000 ; wipe and retract
G1 E2979.67833 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z77.000 F30000.000 ; lift Z
G1 X-137.832 Y-85.311 F30000.000 ; move to first infill point
G1 Z57.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X137.775 Y-85.311 E860.71847 F4200.000 ; infill
G1 X137.775 Y85.296 E1393.46103 ; infill
G1 X-137.832 Y85.296 E2254.07951 ; infill
G1 X-137.832 Y-83.961 E2782.60652 ; infill
G1 F24000
G1 X-137.832 Y-85.311 F30000.000 ; move to first wipe and retract point
G1 X137.775 Y-85.311 E0.0 F4200.000 ; wipe and retract
G1 E2782.50652 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z77.000 F30000.000 ; lift Z
G1 X-129.956 Y-77.436 F30000.000 ; move to first infill point
G1 Z57.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X129.900 Y-77.436 E811.53407 F4200.000 ; infill
G1 X129.900 Y77.420 E1295.09223 ; infill
G1 X-129.956 Y77.420 E2106.52631 ; infill
G1 X-129.956 Y-76.086 E2585.86892 ; infill
G1 F24000
G1 X-129.956 Y-77.436 F30000.000 ; move to first wipe and retract point
G1 X129.900 Y-77.436 E0.0 F4200.000 ; wipe and retract
G1 E2585.76892 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z77.000 F30000.000 ; lift Z
G1 X-153.572 Y-101.072 F30000.000 ; move to first infill point
G1 Z60.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X153.572 Y-101.072 E959.19583 F4200.000 ; infill
G1 X153.572 Y101.072 E1590.41574 ; infill
G1 X-153.572 Y101.072 E2549.51156 ; infill
G1 X-153.572 Y-99.722 E3176.51593 ; infill
G1 F24000
G1 X-153.572 Y-101.072 F30000.000 ; move to first wipe and retract point
G1 X153.572 Y-101.072 E0.0 F4200.000 ; wipe and retract
G1 E3176.41593 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z80.000 F30000.000 ; lift Z
G1 X-145.696 Y-93.196 F30000.000 ; move to first infill point
G1 Z60.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X145.696 Y-93.196 E910.01143 F4200.000 ; infill
G1 X145.696 Y93.196 E1492.04694 ; infill
G1 X-145.696 Y93.196 E2401.95836 ; infill
G1 X-145.696 Y-91.846 E2979.77833 ; infill
G1 F24000
G1 X-145.696 Y-93.196 F30000.000 ; move to first wipe and retract point
G1 X145.696 Y-93.196 E0.0 F4200.000 ; wipe and retract
G1 E2979.67833 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z80.000 F30000.000 ; lift Z
G1 X-137.832 Y-85.311 F30000.000 ; move to first infill point
G1 Z60.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X137.775 Y-85.311 E860.71847 F4200.000 ; infill
G1 X137.775 Y85.296 E1393.46103 ; infill
G1 X-137.832 Y85.296 E2254.07951 ; infill
G1 X-137.832 Y-83.961 E2782.60652 ; infill
G1 F24000
G1 X-137.832 Y-85.311 F30000.000 ; move to first wipe and retract point
G1 X137.775 Y-85.311 E0.0 F4200.000 ; wipe and retract
G1 E2782.50652 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z80.000 F30000.000 ; lift Z
G1 X-129.956 Y-77.436 F30000.000 ; move to first infill point
G1 Z60.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X129.900 Y-77.436 E811.53407 F4200.000 ; infill
G1 X129.900 Y77.420 E1295.09223 ; infill
G1 X-129.956 Y77.420 E2106.52631 ; infill
G1 X-129.956 Y-76.086 E2585.86892 ; infill
G1 F24000
G1 X-129.956 Y-77.436 F30000.000 ; move to first wipe and retract point
G1 X129.900 Y-77.436 E0.0 F4200.000 ; wipe and retract
G1 E2585.76892 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z80.000 F30000.000 ; lift Z
G1 X-153.572 Y-101.072 F30000.000 ; move to first infill point
G1 Z63.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X153.572 Y-101.072 E959.19583 F4200.000 ; infill
G1 X153.572 Y101.072 E1590.41574 ; infill
G1 X-153.572 Y101.072 E2549.51156 ; infill
G1 X-153.572 Y-99.722 E3176.51593 ; infill
G1 F24000
G1 X-153.572 Y-101.072 F30000.000 ; move to first wipe and retract point
G1 X153.572 Y-101.072 E0.0 F4200.000 ; wipe and retract
G1 E3176.41593 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z83.000 F30000.000 ; lift Z
G1 X-145.696 Y-93.196 F30000.000 ; move to first infill point
G1 Z63.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X145.696 Y-93.196 E910.01143 F4200.000 ; infill
G1 X145.696 Y93.196 E1492.04694 ; infill
G1 X-145.696 Y93.196 E2401.95836 ; infill
G1 X-145.696 Y-91.846 E2979.77833 ; infill
G1 F24000
G1 X-145.696 Y-93.196 F30000.000 ; move to first wipe and retract point
G1 X145.696 Y-93.196 E0.0 F4200.000 ; wipe and retract
G1 E2979.67833 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z83.000 F30000.000 ; lift Z
G1 X-137.832 Y-85.311 F30000.000 ; move to first infill point
G1 Z63.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X137.775 Y-85.311 E860.71847 F4200.000 ; infill
G1 X137.775 Y85.296 E1393.46103 ; infill
G1 X-137.832 Y85.296 E2254.07951 ; infill
G1 X-137.832 Y-83.961 E2782.60652 ; infill
G1 F24000
G1 X-137.832 Y-85.311 F30000.000 ; move to first wipe and retract point
G1 X137.775 Y-85.311 E0.0 F4200.000 ; wipe and retract
G1 E2782.50652 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z83.000 F30000.000 ; lift Z
G1 X-129.956 Y-77.436 F30000.000 ; move to first infill point
G1 Z63.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X129.900 Y-77.436 E811.53407 F4200.000 ; infill
G1 X129.900 Y77.420 E1295.09223 ; infill
G1 X-129.956 Y77.420 E2106.52631 ; infill
G1 X-129.956 Y-76.086 E2585.86892 ; infill
G1 F24000
G1 X-129.956 Y-77.436 F30000.000 ; move to first wipe and retract point
G1 X129.900 Y-77.436 E0.0 F4200.000 ; wipe and retract
G1 E2585.76892 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z83.000 F30000.000 ; lift Z
G1 X-153.572 Y-101.072 F30000.000 ; move to first infill point
G1 Z66.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X153.572 Y-101.072 E959.19583 F4200.000 ; infill
G1 X153.572 Y101.072 E1590.41574 ; infill
G1 X-153.572 Y101.072 E2549.51156 ; infill
G1 X-153.572 Y-99.722 E3176.51593 ; infill
G1 F24000
G1 X-153.572 Y-101.072 F30000.000 ; move to first wipe and retract point
G1 X153.572 Y-101.072 E0.0 F4200.000 ; wipe and retract
G1 E3176.41593 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z86.000 F30000.000 ; lift Z
G1 X-145.696 Y-93.196 F30000.000 ; move to first infill point
G1 Z66.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X145.696 Y-93.196 E910.01143 F4200.000 ; infill
G1 X145.696 Y93.196 E1492.04694 ; infill
G1 X-145.696 Y93.196 E2401.95836 ; infill
G1 X-145.696 Y-91.846 E2979.77833 ; infill
G1 F24000
G1 X-145.696 Y-93.196 F30000.000 ; move to first wipe and retract point
G1 X145.696 Y-93.196 E0.0 F4200.000 ; wipe and retract
G1 E2979.67833 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z86.000 F30000.000 ; lift Z
G1 X-137.832 Y-85.311 F30000.000 ; move to first infill point
G1 Z66.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X137.775 Y-85.311 E860.71847 F4200.000 ; infill
G1 X137.775 Y85.296 E1393.46103 ; infill
G1 X-137.832 Y85.296 E2254.07951 ; infill
G1 X-137.832 Y-83.961 E2782.60652 ; infill
G1 F24000
G1 X-137.832 Y-85.311 F30000.000 ; move to first wipe and retract point
G1 X137.775 Y-85.311 E0.0 F4200.000 ; wipe and retract
G1 E2782.50652 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z86.000 F30000.000 ; lift Z
G1 X-129.956 Y-77.436 F30000.000 ; move to first infill point
G1 Z66.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X129.900 Y-77.436 E811.53407 F4200.000 ; infill
G1 X129.900 Y77.420 E1295.09223 ; infill
G1 X-129.956 Y77.420 E2106.52631 ; infill
G1 X-129.956 Y-76.086 E2585.86892 ; infill
G1 F24000
G1 X-129.956 Y-77.436 F30000.000 ; move to first wipe and retract point
G1 X129.900 Y-77.436 E0.0 F4200.000 ; wipe and retract
G1 E2585.76892 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z86.000 F30000.000 ; lift Z
G1 X-153.572 Y-101.072 F30000.000 ; move to first infill point
G1 Z69.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X153.572 Y-101.072 E959.19583 F4200.000 ; infill
G1 X153.572 Y101.072 E1590.41574 ; infill
G1 X-153.572 Y101.072 E2549.51156 ; infill
G1 X-153.572 Y-99.722 E3176.51593 ; infill
G1 F24000
G1 X-153.572 Y-101.072 F30000.000 ; move to first wipe and retract point
G1 X153.572 Y-101.072 E0.0 F4200.000 ; wipe and retract
G1 E3176.41593 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z89.000 F30000.000 ; lift Z
G1 X-145.696 Y-93.196 F30000.000 ; move to first infill point
G1 Z69.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X145.696 Y-93.196 E910.01143 F4200.000 ; infill
G1 X145.696 Y93.196 E1492.04694 ; infill
G1 X-145.696 Y93.196 E2401.95836 ; infill
G1 X-145.696 Y-91.846 E2979.77833 ; infill
G1 F24000
G1 X-145.696 Y-93.196 F30000.000 ; move to first wipe and retract point
G1 X145.696 Y-93.196 E0.0 F4200.000 ; wipe and retract
G1 E2979.67833 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z89.000 F30000.000 ; lift Z
G1 X-137.832 Y-85.311 F30000.000 ; move to first infill point
G1 Z69.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X137.775 Y-85.311 E860.71847 F4200.000 ; infill
G1 X137.775 Y85.296 E1393.46103 ; infill
G1 X-137.832 Y85.296 E2254.07951 ; infill
G1 X-137.832 Y-83.961 E2782.60652 ; infill
G1 F24000
G1 X-137.832 Y-85.311 F30000.000 ; move to first wipe and retract point
G1 X137.775 Y-85.311 E0.0 F4200.000 ; wipe and retract
G1 E2782.50652 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z89.000 F30000.000 ; lift Z
G1 X-129.956 Y-77.436 F30000.000 ; move to first infill point
G1 Z69.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X129.900 Y-77.436 E811.53407 F4200.000 ; infill
G1 X129.900 Y77.420 E1295.09223 ; infill
G1 X-129.956 Y77.420 E2106.52631 ; infill
G1 X-129.956 Y-76.086 E2585.86892 ; infill
G1 F24000
G1 X-129.956 Y-77.436 F30000.000 ; move to first wipe and retract point
G1 X129.900 Y-77.436 E0.0 F4200.000 ; wipe and retract
G1 E2585.76892 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z89.000 F30000.000 ; lift Z
G1 X-153.572 Y-101.072 F30000.000 ; move to first infill point
G1 Z72.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X153.572 Y-101.072 E959.19583 F4200.000 ; infill
G1 X153.572 Y101.072 E1590.41574 ; infill
G1 X-153.572 Y101.072 E2549.51156 ; infill
G1 X-153.572 Y-99.722 E3176.51593 ; infill
G1 F24000
G1 X-153.572 Y-101.072 F30000.000 ; move to first wipe and retract point
G1 X153.572 Y-101.072 E0.0 F4200.000 ; wipe and retract
G1 E3176.41593 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z92.000 F30000.000 ; lift Z
G1 X-145.696 Y-93.196 F30000.000 ; move to first infill point
G1 Z72.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X145.696 Y-93.196 E910.01143 F4200.000 ; infill
G1 X145.696 Y93.196 E1492.04694 ; infill
G1 X-145.696 Y93.196 E2401.95836 ; infill
G1 X-145.696 Y-91.846 E2979.77833 ; infill
G1 F24000
G1 X-145.696 Y-93.196 F30000.000 ; move to first wipe and retract point
G1 X145.696 Y-93.196 E0.0 F4200.000 ; wipe and retract
G1 E2979.67833 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z92.000 F30000.000 ; lift Z
G1 X-137.832 Y-85.311 F30000.000 ; move to first infill point
G1 Z72.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X137.775 Y-85.311 E860.71847 F4200.000 ; infill
G1 X137.775 Y85.296 E1393.46103 ; infill
G1 X-137.832 Y85.296 E2254.07951 ; infill
G1 X-137.832 Y-83.961 E2782.60652 ; infill
G1 F24000
G1 X-137.832 Y-85.311 F30000.000 ; move to first wipe and retract point
G1 X137.775 Y-85.311 E0.0 F4200.000 ; wipe and retract
G1 E2782.50652 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z92.000 F30000.000 ; lift Z
G1 X-129.956 Y-77.436 F30000.000 ; move to first infill point
G1 Z72.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X129.900 Y-77.436 E811.53407 F4200.000 ; infill
G1 X129.900 Y77.420 E1295.09223 ; infill
G1 X-129.956 Y77.420 E2106.52631 ; infill
G1 X-129.956 Y-76.086 E2585.86892 ; infill
G1 F24000
G1 X-129.956 Y-77.436 F30000.000 ; move to first wipe and retract point
G1 X129.900 Y-77.436 E0.0 F4200.000 ; wipe and retract
G1 E2585.76892 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z92.000 F30000.000 ; lift Z
G1 X-153.572 Y-101.072 F30000.000 ; move to first infill point
G1 Z75.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X153.572 Y-101.072 E959.19583 F4200.000 ; infill
G1 X153.572 Y101.072 E1590.41574 ; infill
G1 X-153.572 Y101.072 E2549.51156 ; infill
G1 X-153.572 Y-99.722 E3176.51593 ; infill
G1 F24000
G1 X-153.572 Y-101.072 F30000.000 ; move to first wipe and retract point
G1 X153.572 Y-101.072 E0.0 F4200.000 ; wipe and retract
G1 E3176.41593 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z95.000 F30000.000 ; lift Z
G1 X-145.696 Y-93.196 F30000.000 ; move to first infill point
G1 Z75.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X145.696 Y-93.196 E910.01143 F4200.000 ; infill
G1 X145.696 Y93.196 E1492.04694 ; infill
G1 X-145.696 Y93.196 E2401.95836 ; infill
G1 X-145.696 Y-91.846 E2979.77833 ; infill
G1 F24000
G1 X-145.696 Y-93.196 F30000.000 ; move to first wipe and retract point
G1 X145.696 Y-93.196 E0.0 F4200.000 ; wipe and retract
G1 E2979.67833 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z95.000 F30000.000 ; lift Z
G1 X-137.832 Y-85.311 F30000.000 ; move to first infill point
G1 Z75.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X137.775 Y-85.311 E860.71847 F4200.000 ; infill
G1 X137.775 Y85.296 E1393.46103 ; infill
G1 X-137.832 Y85.296 E2254.07951 ; infill
G1 X-137.832 Y-83.961 E2782.60652 ; infill
G1 F24000
G1 X-137.832 Y-85.311 F30000.000 ; move to first wipe and retract point
G1 X137.775 Y-85.311 E0.0 F4200.000 ; wipe and retract
G1 E2782.50652 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z95.000 F30000.000 ; lift Z
G1 X-129.956 Y-77.436 F30000.000 ; move to first infill point
G1 Z75.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X129.900 Y-77.436 E811.53407 F4200.000 ; infill
G1 X129.900 Y77.420 E1295.09223 ; infill
G1 X-129.956 Y77.420 E2106.52631 ; infill
G1 X-129.956 Y-76.086 E2585.86892 ; infill
G1 F24000
G1 X-129.956 Y-77.436 F30000.000 ; move to first wipe and retract point
G1 X129.900 Y-77.436 E0.0 F4200.000 ; wipe and retract
G1 E2585.76892 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z95.000 F30000.000 ; lift Z
G1 X-153.572 Y-101.072 F30000.000 ; move to first infill point
G1 Z78.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X153.572 Y-101.072 E959.19583 F4200.000 ; infill
G1 X153.572 Y101.072 E1590.41574 ; infill
G1 X-153.572 Y101.072 E2549.51156 ; infill
G1 X-153.572 Y-99.722 E3176.51593 ; infill
G1 F24000
G1 X-153.572 Y-101.072 F30000.000 ; move to first wipe and retract point
G1 X153.572 Y-101.072 E0.0 F4200.000 ; wipe and retract
G1 E3176.41593 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z98.000 F30000.000 ; lift Z
G1 X-145.696 Y-93.196 F30000.000 ; move to first infill point
G1 Z78.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X145.696 Y-93.196 E910.01143 F4200.000 ; infill
G1 X145.696 Y93.196 E1492.04694 ; infill
G1 X-145.696 Y93.196 E2401.95836 ; infill
G1 X-145.696 Y-91.846 E2979.77833 ; infill
G1 F24000
G1 X-145.696 Y-93.196 F30000.000 ; move to first wipe and retract point
G1 X145.696 Y-93.196 E0.0 F4200.000 ; wipe and retract
G1 E2979.67833 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z98.000 F30000.000 ; lift Z
G1 X-137.832 Y-85.311 F30000.000 ; move to first infill point
G1 Z78.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X137.775 Y-85.311 E860.71847 F4200.000 ; infill
G1 X137.775 Y85.296 E1393.46103 ; infill
G1 X-137.832 Y85.296 E2254.07951 ; infill
G1 X-137.832 Y-83.961 E2782.60652 ; infill
G1 F24000
G1 X-137.832 Y-85.311 F30000.000 ; move to first wipe and retract point
G1 X137.775 Y-85.311 E0.0 F4200.000 ; wipe and retract
G1 E2782.50652 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z98.000 F30000.000 ; lift Z
G1 X-129.956 Y-77.436 F30000.000 ; move to first infill point
G1 Z78.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X129.900 Y-77.436 E811.53407 F4200.000 ; infill
G1 X129.900 Y77.420 E1295.09223 ; infill
G1 X-129.956 Y77.420 E2106.52631 ; infill
G1 X-129.956 Y-76.086 E2585.86892 ; infill
G1 F24000
G1 X-129.956 Y-77.436 F30000.000 ; move to first wipe and retract point
G1 X129.900 Y-77.436 E0.0 F4200.000 ; wipe and retract
G1 E2585.76892 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z98.000 F30000.000 ; lift Z
G1 X-153.572 Y-101.072 F30000.000 ; move to first infill point
G1 Z81.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X153.572 Y-101.072 E959.19583 F4200.000 ; infill
G1 X153.572 Y101.072 E1590.41574 ; infill
G1 X-153.572 Y101.072 E2549.51156 ; infill
G1 X-153.572 Y-99.722 E3176.51593 ; infill
G1 F24000
G1 X-153.572 Y-101.072 F30000.000 ; move to first wipe and retract point
G1 X153.572 Y-101.072 E0.0 F4200.000 ; wipe and retract
G1 E3176.41593 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z101.000 F30000.000 ; lift Z
G1 X-145.696 Y-93.196 F30000.000 ; move to first infill point
G1 Z81.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X145.696 Y-93.196 E910.01143 F4200.000 ; infill
G1 X145.696 Y93.196 E1492.04694 ; infill
G1 X-145.696 Y93.196 E2401.95836 ; infill
G1 X-145.696 Y-91.846 E2979.77833 ; infill
G1 F24000
G1 X-145.696 Y-93.196 F30000.000 ; move to first wipe and retract point
G1 X145.696 Y-93.196 E0.0 F4200.000 ; wipe and retract
G1 E2979.67833 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z101.000 F30000.000 ; lift Z
G1 X-137.832 Y-85.311 F30000.000 ; move to first infill point
G1 Z81.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X137.775 Y-85.311 E860.71847 F4200.000 ; infill
G1 X137.775 Y85.296 E1393.46103 ; infill
G1 X-137.832 Y85.296 E2254.07951 ; infill
G1 X-137.832 Y-83.961 E2782.60652 ; infill
G1 F24000
G1 X-137.832 Y-85.311 F30000.000 ; move to first wipe and retract point
G1 X137.775 Y-85.311 E0.0 F4200.000 ; wipe and retract
G1 E2782.50652 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z101.000 F30000.000 ; lift Z
G1 X-129.956 Y-77.436 F30000.000 ; move to first infill point
G1 Z81.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X129.900 Y-77.436 E811.53407 F4200.000 ; infill
G1 X129.900 Y77.420 E1295.09223 ; infill
G1 X-129.956 Y77.420 E2106.52631 ; infill
G1 X-129.956 Y-76.086 E2585.86892 ; infill
G1 F24000
G1 X-129.956 Y-77.436 F30000.000 ; move to first wipe and retract point
G1 X129.900 Y-77.436 E0.0 F4200.000 ; wipe and retract
G1 E2585.76892 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z101.000 F30000.000 ; lift Z
G1 X-153.572 Y-101.072 F30000.000 ; move to first infill point
G1 Z84.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X153.572 Y-101.072 E959.19583 F4200.000 ; infill
G1 X153.572 Y101.072 E1590.41574 ; infill
G1 X-153.572 Y101.072 E2549.51156 ; infill
G1 X-153.572 Y-99.722 E3176.51593 ; infill
G1 F24000
G1 X-153.572 Y-101.072 F30000.000 ; move to first wipe and retract point
G1 X153.572 Y-101.072 E0.0 F4200.000 ; wipe and retract
G1 E3176.41593 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z104.000 F30000.000 ; lift Z
G1 X-145.696 Y-93.196 F30000.000 ; move to first infill point
G1 Z84.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X145.696 Y-93.196 E910.01143 F4200.000 ; infill
G1 X145.696 Y93.196 E1492.04694 ; infill
G1 X-145.696 Y93.196 E2401.95836 ; infill
G1 X-145.696 Y-91.846 E2979.77833 ; infill
G1 F24000
G1 X-145.696 Y-93.196 F30000.000 ; move to first wipe and retract point
G1 X145.696 Y-93.196 E0.0 F4200.000 ; wipe and retract
G1 E2979.67833 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z104.000 F30000.000 ; lift Z
G1 X-137.832 Y-85.311 F30000.000 ; move to first infill point
G1 Z84.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X137.775 Y-85.311 E860.71847 F4200.000 ; infill
G1 X137.775 Y85.296 E1393.46103 ; infill
G1 X-137.832 Y85.296 E2254.07951 ; infill
G1 X-137.832 Y-83.961 E2782.60652 ; infill
G1 F24000
G1 X-137.832 Y-85.311 F30000.000 ; move to first wipe and retract point
G1 X137.775 Y-85.311 E0.0 F4200.000 ; wipe and retract
G1 E2782.50652 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z104.000 F30000.000 ; lift Z
G1 X-129.956 Y-77.436 F30000.000 ; move to first infill point
G1 Z84.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X129.900 Y-77.436 E811.53407 F4200.000 ; infill
G1 X129.900 Y77.420 E1295.09223 ; infill
G1 X-129.956 Y77.420 E2106.52631 ; infill
G1 X-129.956 Y-76.086 E2585.86892 ; infill
G1 F24000
G1 X-129.956 Y-77.436 F30000.000 ; move to first wipe and retract point
G1 X129.900 Y-77.436 E0.0 F4200.000 ; wipe and retract
G1 E2585.76892 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z104.000 F30000.000 ; lift Z
G1 X-153.572 Y-101.072 F30000.000 ; move to first infill point
G1 Z87.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X153.572 Y-101.072 E959.19583 F4200.000 ; infill
G1 X153.572 Y101.072 E1590.41574 ; infill
G1 X-153.572 Y101.072 E2549.51156 ; infill
G1 X-153.572 Y-99.722 E3176.51593 ; infill
G1 F24000
G1 X-153.572 Y-101.072 F30000.000 ; move to first wipe and retract point
G1 X153.572 Y-101.072 E0.0 F4200.000 ; wipe and retract
G1 E3176.41593 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z107.000 F30000.000 ; lift Z
G1 X-145.696 Y-93.196 F30000.000 ; move to first infill point
G1 Z87.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X145.696 Y-93.196 E910.01143 F4200.000 ; infill
G1 X145.696 Y93.196 E1492.04694 ; infill
G1 X-145.696 Y93.196 E2401.95836 ; infill
G1 X-145.696 Y-91.846 E2979.77833 ; infill
G1 F24000
G1 X-145.696 Y-93.196 F30000.000 ; move to first wipe and retract point
G1 X145.696 Y-93.196 E0.0 F4200.000 ; wipe and retract
G1 E2979.67833 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z107.000 F30000.000 ; lift Z
G1 X-137.832 Y-85.311 F30000.000 ; move to first infill point
G1 Z87.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X137.775 Y-85.311 E860.71847 F4200.000 ; infill
G1 X137.775 Y85.296 E1393.46103 ; infill
G1 X-137.832 Y85.296 E2254.07951 ; infill
G1 X-137.832 Y-83.961 E2782.60652 ; infill
G1 F24000
G1 X-137.832 Y-85.311 F30000.000 ; move to first wipe and retract point
G1 X137.775 Y-85.311 E0.0 F4200.000 ; wipe and retract
G1 E2782.50652 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z107.000 F30000.000 ; lift Z
G1 X-129.956 Y-77.436 F30000.000 ; move to first infill point
G1 Z87.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X129.900 Y-77.436 E811.53407 F4200.000 ; infill
G1 X129.900 Y77.420 E1295.09223 ; infill
G1 X-129.956 Y77.420 E2106.52631 ; infill
G1 X-129.956 Y-76.086 E2585.86892 ; infill
G1 F24000
G1 X-129.956 Y-77.436 F30000.000 ; move to first wipe and retract point
G1 X129.900 Y-77.436 E0.0 F4200.000 ; wipe and retract
G1 E2585.76892 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z107.000 F30000.000 ; lift Z
G1 X-153.572 Y-101.072 F30000.000 ; move to first infill point
G1 Z90.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X153.572 Y-101.072 E959.19583 F4200.000 ; infill
G1 X153.572 Y101.072 E1590.41574 ; infill
G1 X-153.572 Y101.072 E2549.51156 ; infill
G1 X-153.572 Y-99.722 E3176.51593 ; infill
G1 F24000
G1 X-153.572 Y-101.072 F30000.000 ; move to first wipe and retract point
G1 X153.572 Y-101.072 E0.0 F4200.000 ; wipe and retract
G1 E3176.41593 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z110.000 F30000.000 ; lift Z
G1 X-145.696 Y-93.196 F30000.000 ; move to first infill point
G1 Z90.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X145.696 Y-93.196 E910.01143 F4200.000 ; infill
G1 X145.696 Y93.196 E1492.04694 ; infill
G1 X-145.696 Y93.196 E2401.95836 ; infill
G1 X-145.696 Y-91.846 E2979.77833 ; infill
G1 F24000
G1 X-145.696 Y-93.196 F30000.000 ; move to first wipe and retract point
G1 X145.696 Y-93.196 E0.0 F4200.000 ; wipe and retract
G1 E2979.67833 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z110.000 F30000.000 ; lift Z
G1 X-137.832 Y-85.311 F30000.000 ; move to first infill point
G1 Z90.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X137.775 Y-85.311 E860.71847 F4200.000 ; infill
G1 X137.775 Y85.296 E1393.46103 ; infill
G1 X-137.832 Y85.296 E2254.07951 ; infill
G1 X-137.832 Y-83.961 E2782.60652 ; infill
G1 F24000
G1 X-137.832 Y-85.311 F30000.000 ; move to first wipe and retract point
G1 X137.775 Y-85.311 E0.0 F4200.000 ; wipe and retract
G1 E2782.50652 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z110.000 F30000.000 ; lift Z
G1 X-129.956 Y-77.436 F30000.000 ; move to first infill point
G1 Z90.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X129.900 Y-77.436 E811.53407 F4200.000 ; infill
G1 X129.900 Y77.420 E1295.09223 ; infill
G1 X-129.956 Y77.420 E2106.52631 ; infill
G1 X-129.956 Y-76.086 E2585.86892 ; infill
G1 F24000
G1 X-129.956 Y-77.436 F30000.000 ; move to first wipe and retract point
G1 X129.900 Y-77.436 E0.0 F4200.000 ; wipe and retract
G1 E2585.76892 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z110.000 F30000.000 ; lift Z
G1 X-153.572 Y-101.072 F30000.000 ; move to first infill point
G1 Z93.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X153.572 Y-101.072 E959.19583 F4200.000 ; infill
G1 X153.572 Y101.072 E1590.41574 ; infill
G1 X-153.572 Y101.072 E2549.51156 ; infill
G1 X-153.572 Y-99.722 E3176.51593 ; infill
G1 F24000
G1 X-153.572 Y-101.072 F30000.000 ; move to first wipe and retract point
G1 X153.572 Y-101.072 E0.0 F4200.000 ; wipe and retract
G1 E3176.41593 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z113.000 F30000.000 ; lift Z
G1 X-145.696 Y-93.196 F30000.000 ; move to first infill point
G1 Z93.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X145.696 Y-93.196 E910.01143 F4200.000 ; infill
G1 X145.696 Y93.196 E1492.04694 ; infill
G1 X-145.696 Y93.196 E2401.95836 ; infill
G1 X-145.696 Y-91.846 E2979.77833 ; infill
G1 F24000
G1 X-145.696 Y-93.196 F30000.000 ; move to first wipe and retract point
G1 X145.696 Y-93.196 E0.0 F4200.000 ; wipe and retract
G1 E2979.67833 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z113.000 F30000.000 ; lift Z
G1 X-137.832 Y-85.311 F30000.000 ; move to first infill point
G1 Z93.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X137.775 Y-85.311 E860.71847 F4200.000 ; infill
G1 X137.775 Y85.296 E1393.46103 ; infill
G1 X-137.832 Y85.296 E2254.07951 ; infill
G1 X-137.832 Y-83.961 E2782.60652 ; infill
G1 F24000
G1 X-137.832 Y-85.311 F30000.000 ; move to first wipe and retract point
G1 X137.775 Y-85.311 E0.0 F4200.000 ; wipe and retract
G1 E2782.50652 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z113.000 F30000.000 ; lift Z
G1 X-129.956 Y-77.436 F30000.000 ; move to first infill point
G1 Z93.000 F30000.000 ; restore layer Z
G1 E0.10000 F4200.00000 ; unretract
G1 X129.900 Y-77.436 E811.53407 F4200.000 ; infill
G1 X129.900 Y77.420 E1295.09223 ; infill
G1 X-129.956 Y77.420 E2106.52631 ; infill
G1 X-129.956 Y-76.086 E2585.86892 ; infill
G1 F24000
G1 X-129.956 Y-77.436 F30000.000 ; move to first wipe and retract point
G1 X129.900 Y-77.436 E0.0 F4200.000 ; wipe and retract
G1 E2585.76892 F4200.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z113.000 F30000.000 ; lift Z

; filament used = 357255.5mm (2696.4cm3)

; avoid_crossing_perimeters = 0
; bed_shape = 908.993x95.539,894.027x190.031,869.266x282.442,834.981x371.757,791.547x457,739.442x537.236,679.234x611.585,611.585x679.234,537.236x739.442,457x791.547,371.757x834.981,282.442x869.266,190.031x894.027,95.539x908.993,0x914,-95.539x908.993,-190.031x894.027,-282.442x869.266,-371.757x834.981,-457x791.547,-537.236x739.442,-611.585x679.234,-679.234x611.585,-739.442x537.236,-791.547x457,-834.981x371.757,-869.266x282.442,-894.027x190.031,-908.993x95.539,-914x0,-908.993x-95.539,-894.027x-190.031,-869.266x-282.442,-834.981x-371.757,-791.547x-457,-739.442x-537.236,-679.234x-611.585,-611.585x-679.234,-537.236x-739.442,-457x-791.547,-371.757x-834.981,-282.442x-869.266,-190.031x-894.027,-95.539x-908.993,0x-914,95.539x-908.993,190.031x-894.027,282.442x-869.266,371.757x-834.981,457x-791.547,537.236x-739.442,611.585x-679.234,679.234x-611.585,739.442x-537.236,791.547x-457,834.981x-371.757,869.266x-282.442,894.027x-190.031,908.993x-95.539,914x0
; bed_temperature = 95
; before_layer_gcode = 
; bridge_acceleration = 0
; bridge_fan_speed = 100
; brim_width = 0
; complete_objects = 0
; cooling = 0
; default_acceleration = 0
; disable_fan_first_layers = 6
; duplicate_distance = 6
; end_gcode = 
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; fan_always_on = 0
; fan_below_layer_time = 5
; filament_colour = #A8A8A8
; filament_diameter = 3.1
; first_layer_acceleration = 0
; first_layer_bed_temperature = 95
; first_layer_extrusion_width = 8.5
; first_layer_speed = 100%
; first_layer_temperature = 225
; gcode_arcs = 0
; gcode_comments = 1
; gcode_flavor = reprap
; infill_acceleration = 0
; infill_first = 0
; layer_gcode = 
; max_fan_speed = 100
; max_print_speed = 100
; max_volumetric_speed = 0
; min_fan_speed = 35
; min_print_speed = 10
; min_skirt_length = 0
; notes = For G-Code Optimization - See Desktop>Robot Projects>Preparing To Print>Printing Instructions
; nozzle_diameter = 9
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = [input_filename_base].gcode
; perimeter_acceleration = 0
; post_process = 
; pressure_advance = 0
; resolution = 0
; retract_before_travel = 2
; retract_layer_change = 1
; retract_length = 0.1
; retract_length_toolchange = 10
; retract_lift = 20
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 70
; skirt_distance = 6
; skirt_height = 1
; skirts = 0
; slowdown_below_layer_time = 0
; spiral_vase = 0
; standby_temperature_delta = -5
; start_gcode = 
; temperature = 225
; threads = 8
; toolchange_gcode = 
; travel_speed = 500
; use_firmware_retraction = 0
; use_relative_e_distances = 0
; use_volumetric_e = 0
; vibration_limit = 0
; wipe = 1
; z_offset = 0
; dont_support_bridges = 1
; extrusion_width = 8.5
; first_layer_height = 3
; infill_only_where_needed = 0
; interface_shells = 0
; layer_height = 3
; raft_layers = 0
; seam_position = aligned
; support_material = 0
; support_material_angle = 0
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0
; support_material_interface_extruder = 1
; support_material_interface_layers = 3
; support_material_interface_spacing = 0
; support_material_interface_speed = 100%
; support_material_pattern = pillars
; support_material_spacing = 2.5
; support_material_speed = 70
; support_material_threshold = 60
; xy_size_compensation = 0
; bottom_solid_layers = 0
; bridge_flow_ratio = 1
; bridge_speed = 60
; external_fill_pattern = rectilinear
; external_perimeter_extrusion_width = 11
; external_perimeter_speed = 100%
; external_perimeters_first = 0
; extra_perimeters = 0
; fill_angle = 90
; fill_density = 100%
; fill_pattern = concentric
; gap_fill_speed = 60
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 8.5
; infill_overlap = 10%
; infill_speed = 70
; overhangs = 0
; perimeter_extruder = 1
; perimeter_extrusion_width = 11
; perimeter_speed = 70
; perimeters = 0
; small_perimeter_speed = 100%
; solid_infill_below_area = 70
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0
; solid_infill_speed = 100%
; thin_walls = 1
; top_infill_extrusion_width = 0
; top_solid_infill_speed = 100%
; top_solid_layers = 0
